#!/usr/bin/python

import matplotlib.pyplot as plt
import sys
import re
import getopt

marker = '.'
opts, args = getopt.getopt(sys.argv[1:], 'l')
for o, a in opts:
  if o == '-l':
    marker = '.-'

x = []
y = []   
for line in sys.stdin:
  line = line.strip()
  vals = re.split(r'\s+|\s*,\s*', line)
  x.append(vals[0])
  y.append(vals[1])
plt.plot(x, y, marker)
plt.minorticks_on()
plt.grid(which='both', color='#aaaaaa')
plt.savefig(sys.stdout, format='png')
